/**
 * Pure validation + filename helpers for admin merchant logo uploads.
 *
 * Logos are stored on the local disk under `public/uploads/merchant-logos`
 * (self-hosted setup, no object storage). Keeping the validation rules and the
 * extension mapping here means they can be unit-tested without touching the
 * file system or Next.js request plumbing.
 */

export const MERCHANT_LOGO_MAX_BYTES = 1024 * 1024; // 1 MB

/** Allowed content types mapped to their canonical file extension. */
export const MERCHANT_LOGO_CONTENT_TYPES: Record<string, string> = {
  "image/png": "png",
  "image/jpeg": "jpg",
  "image/webp": "webp",
  "image/svg+xml": "svg"
};

export type LogoValidationResult =
  | { ok: true; extension: string }
  | { ok: false; reason: string };

/**
 * Validates an uploaded logo by content type and size. Returns the canonical
 * file extension to use when persisting the file.
 */
export function validateMerchantLogo(input: {
  contentType: string;
  sizeBytes: number;
}): LogoValidationResult {
  const contentType = input.contentType.toLowerCase().split(";")[0]?.trim() ?? "";
  const extension = MERCHANT_LOGO_CONTENT_TYPES[contentType];

  if (!extension) {
    return {
      ok: false,
      reason: "Format logo harus PNG, JPG, WEBP, atau SVG."
    };
  }

  if (!Number.isFinite(input.sizeBytes) || input.sizeBytes <= 0) {
    return { ok: false, reason: "File logo kosong." };
  }

  if (input.sizeBytes > MERCHANT_LOGO_MAX_BYTES) {
    return { ok: false, reason: "Ukuran logo maksimal 1MB." };
  }

  return { ok: true, extension };
}

/**
 * Builds a safe, collision-resistant object key for a logo. The id should be a
 * random UUID generated by the caller; we only append the validated extension.
 */
export function buildMerchantLogoFileName(id: string, extension: string): string {
  return `${id}.${extension}`;
}

/** Public URL path the app serves the stored logo from. */
export function buildMerchantLogoPublicPath(fileName: string): string {
  return `/uploads/merchant-logos/${fileName}`;
}

/**
 * Accepts either an absolute http(s) URL or an app-relative path beginning with
 * a single `/`. Used to validate the `logo_url` / `website_url` fields so admins
 * can paste a CDN URL or use an uploaded local path interchangeably.
 */
export function isValidLogoReference(value: string): boolean {
  if (value === "") {
    return true;
  }
  if (value.startsWith("/") && !value.startsWith("//")) {
    return true;
  }
  try {
    const url = new URL(value);
    return url.protocol === "http:" || url.protocol === "https:";
  } catch {
    return false;
  }
}
